### PR TITLE
Create option to only load vim confs once per session

### PR DESCRIPTION
**Pull request by zeertzjq**
Close: #18

### CODE REVIEW

**Comment by zeertzjq** [comment]
It seems there needs to be some changes to the tests.

**Comment by jenterkin** [comment]
> Is it necessary to add a new test?

Yep, I want to make sure things don't suddenly break for other users. I wasn't able to get tests working in a container though so if you don't want to add the test I can do that some time next week.

**Comment by zeertzjq** [comment]
I have added a new test.

**Comment by zeertzjq** [comment]
Closing because I no longer use this plugin.

**Pull request closed without merging**
